In [ ]:
from pathlib import Path
import json
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pprint
from IPython.display import display, HTML

import analysis_utility_funcs as unified_funcs

## This notebook is where :

## 1. we attach human ratings and original scenario texts to our annotator results (to make a `compact_df`) and 
## 2. use it to do the primary harm picking (which makes a `primary_harm_df`). 

## And we save both as CSVs to be loaded in to the Franken analysis notebook whenever needed. (I.E. for Experiments 1A, 1B, 5A, and 5B).

In [2]:
all_FRANKEN_df = []

intensities = ["mild_harm_mild_good", "severe_harm_very_good"]
causal_conditions = ["cc_evitable_action_yes_stories", "cc_evitable_prevention_no_stories", "cc_inevitable_action_yes_stories", "cc_inevitable_prevention_no_stories", "coc_evitable_action_yes_stories", "coc_evitable_prevention_no_stories", "coc_inevitable_action_yes_stories", "coc_inevitable_prevention_no_stories"]

for intensity in intensities:
    for causal_condition in causal_conditions:
        df = unified_funcs.read_all_scenarios(f"../../scenarios_inputs/franken/conditions_{intensity}/{causal_condition}.json", f"../../annotated_outputs/franken_o1o2/conditions_{intensity}/{causal_condition}/")
        all_FRANKEN_df.append(df)
        # SPECIAL - add the intensity and causal_condition as columns to the dataframe
        all_FRANKEN_df[-1]["intensity"] = intensity
        all_FRANKEN_df[-1]["causal_condition"] = causal_condition
all_FRANKEN_df = pd.concat(all_FRANKEN_df, ignore_index=True)
# sort the intensity column by the order of the intensities in the intensities list above
all_FRANKEN_df["intensity"] = pd.Categorical(all_FRANKEN_df["intensity"], categories=intensities, ordered=True)
# sort them by the order of the causal conditions in the causal_conditions list above
all_FRANKEN_df["causal_condition"] = pd.Categorical(all_FRANKEN_df["causal_condition"], categories=causal_conditions, ordered=True)
# sort the dataframe by intensity, then by causal condition, then by SID, then by option --- this is how I think is best to sort it for readability but can be changed up.
all_FRANKEN_df = all_FRANKEN_df.sort_values(by=["intensity","causal_condition", "SID", "option"]).reset_index(drop=True)
# drop all the rows where SID is greater than 9
all_FRANKEN_df = all_FRANKEN_df[all_FRANKEN_df["SID"] <= 9]
display(HTML(all_FRANKEN_df[0:10].to_html()))
print("number of rows in all_FRANKEN_df:", len(all_FRANKEN_df))

number of rows in all_FRANKEN_df: 754

In [3]:
mild_FRANKEN_df = all_FRANKEN_df[all_FRANKEN_df["intensity"] == "mild_harm_mild_good"]
severe_FRANKEN_df = all_FRANKEN_df[all_FRANKEN_df["intensity"] == "severe_harm_very_good"]
print("mild_FRANKEN_df preview:")
display(HTML(mild_FRANKEN_df[0:10].to_html()))
print("number of rows in mild_FRANKEN_df:", len(mild_FRANKEN_df))
print("severe_FRANKEN_df preview:")
display(HTML(severe_FRANKEN_df[0:10].to_html()))
print("number of rows in severe_FRANKEN_df:", len(severe_FRANKEN_df))

mild_FRANKEN_df preview:

number of rows in mild_FRANKEN_df: 309
severe_FRANKEN_df preview:

number of rows in severe_FRANKEN_df: 445

### Step 1 - Load the human ratings into a DF (from Franken Exp 2 for intentionality and permissibility)

In [4]:
exp2_data_path = "../../human_data/franken/exp2_moralperm-intent-rating"
exp2_raw_df = []
# go through all json files in the exp2_data_path
for json_file in Path(exp2_data_path).glob("*.json"):
    # print(f"Processing file: {json_file.name}")
    with open(json_file, 'r') as f:
        curr_batch_list = json.load(f)
        for exp2_item in curr_batch_list:
            exp2_raw_df.append(exp2_item)
# reorder the exp2_raw_df by the "folder_name" key according to the folder_order list
condition_order = [
    "cc_evitable_action_yes",
    "cc_evitable_prevention_no",
    "cc_inevitable_action_yes",
    "cc_inevitable_prevention_no",
    "coc_evitable_action_yes",
    "coc_evitable_prevention_no",
    "coc_inevitable_action_yes",
    "coc_inevitable_prevention_no"
]
exp2_raw_df.sort(key=lambda x: condition_order.index(x["condition"]))
# reorder the exp2_raw_df by the "scenario_id" key in ascending order
exp2_raw_df.sort(key=lambda x: int(x["scenario_id"]))
exp2_raw_df = pd.DataFrame(exp2_raw_df)
# print("Raw DataFrame from Experiment 2:")
# display(HTML(exp2_raw_df[0:2].to_html()))
# print(f"Total number of rows in Exp2 raw DataFrame: {len(exp2_raw_df)}")

human_ratings = pd.read_csv(Path().resolve() / "../../human_data/franken/exp2_moralperm-intent-rating/data_long_format.csv")
human_ratings = human_ratings.drop(columns=['scenario_harm', 'split'])
# count number of unique combinations of scenario_id + causal_structure + evitability + action
exp2_ratings_df = human_ratings.groupby(['scenario_id', 'causal_structure', 'evitability', 'action']).size().reset_index(name='counts') # each scenario got rated by ~20-25 participants
# add a column of average rating of moral permissibility and intention for each unique combination
avg_ratings = human_ratings.groupby(['scenario_id', 'causal_structure', 'evitability', 'action'])[['permissibility_rating', 'intention_rating']].mean().reset_index()
exp2_ratings_df = exp2_ratings_df.merge(avg_ratings, on=['scenario_id', 'causal_structure', 'evitability', 'action'])
exp2_ratings_df = exp2_ratings_df.rename(columns={
    'permissibility_rating': 'avg_permissibility_rating',
    'intention_rating': 'avg_intention_rating'
})
print("\n Explainer (CORRECTED -- see markdown note below on why this differs from the bundled explainer.txt): \n causal_structure (0 for side effect (coc), 1 for means (cc)) \n action (0 for omission i.e. prevention_no, 1 for commission i.e. action_yes) \n evitability (0 for inevitable, 1 for evitable) \n avg_permissibility_rating (average moral permissibility rating for that scenario) \n avg_intention_rating (average intention rating for that scenario)\n")
print("Processed DataFrame with average ratings from Experiment 2:")
display(HTML(exp2_ratings_df[0:6].to_html()))
print(f"Total number of rows in processed Exp2 ratings DataFrame: {len(exp2_ratings_df)}")

 Explainer (CORRECTED -- see markdown note below on why this differs from the bundled explainer.txt):
 causal_structure (0 for side effect (coc), 1 for means (cc))
 action (0 for omission i.e. prevention_no, 1 for commission i.e. action_yes)
 evitability (0 for inevitable, 1 for evitable)
 avg_permissibility_rating (average moral permissibility rating for that scenario)
 avg_intention_rating (average intention rating for that scenario)

Processed DataFrame with average ratings from Experiment 2:

Total number of rows in processed Exp2 ratings DataFrame: 80

### BUG FOUND AND FIXED — `causal_structure` / `evitability` / `action` were inverted

When I read the paper a long time ago, I wrote down this txt file: `human_data/franken/exp2_moralperm-intent-rating/explainer.txt`
```
Causal structure (0 for means, 1 for side effect)
Action (0 for commission, 1 for omission)
Evitability (0 for evitable, 1 for inevitable)
```

**BUT** the Franken paper states the *opposite* coding explicitly (on page 5). I had them flipped!! So all the experiments that use Exp2 human ratings are affected, i.e. 1C, 5A/B, 6.

### Step 2 - Add the human ratings to our mild_FRANKEN_df (ratings only exist for mild scenarios)

In [5]:
# create a new dataframe to hold the merged data
mild_FRANKEN_withhuman_df = mild_FRANKEN_df.copy()
# create new columns for avg_permissibility_rating and avg_intention_rating in the merged_df and initialize them with NaN
mild_FRANKEN_withhuman_df["avg_permissibility_rating"] = np.nan
mild_FRANKEN_withhuman_df["avg_intention_rating"] = np.nan  

# loop through each row in the merged_df and find the corresponding avg ratings from exp2_ratings_df
for idx, row in mild_FRANKEN_withhuman_df.iterrows():
    sid = row["SID"]
    causal_condition = row["causal_condition"]

    # determine the values of causal_structure, evitability, and action based on the causal_condition string.
    # NOTE: FIXED ASSIGNMENTS BELOW!
    if "cc" in causal_condition:
        causal_structure = 1
    elif "coc" in causal_condition:
        causal_structure = 0
    else:
        continue  # skip if neither is found

    if "inevitable" in causal_condition:
        evitability = 0
    elif "evitable" in causal_condition:
        evitability = 1
    else:
        continue  # skip if neither is found

    if "action_yes" in causal_condition:
        action = 1
    elif "prevention_no" in causal_condition:
        action = 0
    else:
        continue  # skip if neither is found

    # find the matching row in exp2_ratings_df
    match = exp2_ratings_df[
        (exp2_ratings_df["scenario_id"] == sid) &
        (exp2_ratings_df["causal_structure"] == causal_structure) &
        (exp2_ratings_df["evitability"] == evitability) &
        (exp2_ratings_df["action"] == action)
    ]

    if not match.empty:
        mild_FRANKEN_withhuman_df.at[idx, "avg_permissibility_rating"] = match.iloc[0]["avg_permissibility_rating"]
        mild_FRANKEN_withhuman_df.at[idx, "avg_intention_rating"] = match.iloc[0]["avg_intention_rating"]

print("Our old mild_FRANKEN_df with average human ratings per scenario added from Experiment 2:")
display(HTML(mild_FRANKEN_withhuman_df[0:10].to_html()))
print(f"Total number of rows in mild_FRANKEN_withhuman_df: {len(mild_FRANKEN_withhuman_df)}")

Our old mild_FRANKEN_df with average human ratings per scenario added from Experiment 2:

Total number of rows in mild_FRANKEN_withhuman_df: 309

### Step 3 -- "compact" the DF i.e. collect all events into one row per scenario, also add in the full scenario text

In [6]:
# create a compact version of the mild_FRANKEN_withhuman_df by collecting all the rows per scenario into a one row. You can find all the rows that belong to a scenario by finding all the rows that have the same SID and causal condition. The df will have all the rows that are in mild_FRANKEN_withhuman_df, but instead of 'event', we will have 'events' where values are a list of all the event strings. Then, values in the C, I, K columns will also be lists of the corresponding C, I, K values for each event, and the utility column will contain a list of dictionaries, one dict for each event. The intensity, causal_condition, avg_permissibility_rating, and avg_intention_rating columns will just take the value from the first row of the scenario group since they are the same across all rows of the same scenario.

mild_FRANKEN_compact_df = mild_FRANKEN_withhuman_df.groupby(["SID", "causal_condition", "option", "being", "intensity", "deontic", "avg_permissibility_rating", "avg_intention_rating"]).agg({
    "event": list,
    "C": list,
    "I": list,
    "K": list,
    "utility": list
}).reset_index()
# reorder the order of the columns to be SID, intensity, causal_condition, option, events, being, C, I, K, utility, avg_permissibility_rating, avg_intention_rating
mild_FRANKEN_compact_df = mild_FRANKEN_compact_df[["SID", "intensity", "causal_condition", "option", "event", "being", "C", "I", "K", "utility", "deontic", "avg_permissibility_rating", "avg_intention_rating"]]
# rename the "event" column to "events" since it now contains a list of events
mild_FRANKEN_compact_df = mild_FRANKEN_compact_df.rename(columns={"event": "events"})


# last thing -- bring in the original scenario text into the mild_FRANKEN_compact_df for easier reference. We need to get them from the JSONs in ../../scenarios_inputs/franken/conditions_mild_harm_mild_good/ where we have eight JSON files corresponding to the eight causal conditions (files have the same names as the causal conditions in the mild_FRANKEN_compact_df). 
scenario_texts = {}
for causal_condition in causal_conditions:
    with open(f"../../scenarios_inputs/franken/conditions_mild_harm_mild_good/{causal_condition}.json", 'r') as f:
        scenarios = json.load(f)
        for scenario in scenarios:
            scenario_texts[(scenario["id"], causal_condition)] = scenario["text"]
# now create a new column in mild_FRANKEN_compact_df called "scenario_text" and fill it by matching the SID and causal_condition with the keys in scenario_texts
mild_FRANKEN_compact_df["scenario_text"] = mild_FRANKEN_compact_df.apply(lambda row: scenario_texts.get((row["SID"], row["causal_condition"]), "N/A"), axis=1)
# reorder the columns to put scenario_text right after causal_condition for easier reference
mild_FRANKEN_compact_df = mild_FRANKEN_compact_df[["SID", "intensity", "causal_condition", "scenario_text", "option", "events", "being", "C", "I", "K", "utility", "deontic", "avg_permissibility_rating", "avg_intention_rating"]]
# group the rows by causal condition and then SID and thats it:
mild_FRANKEN_compact_df = mild_FRANKEN_compact_df.groupby(["causal_condition", "SID"]).first().reset_index()
print("Mild_FRANKEN_compact_df with scenario_text column added:")
display(HTML(mild_FRANKEN_compact_df[0:2].to_html()))
print(f"Total number of rows in mild_FRANKEN_compact_df: {len(mild_FRANKEN_compact_df)}")

# save this df into a csv file for easier reference in the future
mild_FRANKEN_compact_df.to_csv("mild_FRANKEN_compact_df.csv", index=False)

Mild_FRANKEN_compact_df with scenario_text column added:

Total number of rows in mild_FRANKEN_compact_df: 80

### Did the harm-picking from the DF above, index of picked event for each scenario is in `mild_FRANKEN_harm_picks.csv`

### Making a "primary harm picks DF":

In [7]:
# Use the mild_FRANKEN_harm_picks.csv to make a "primary harm DF". Read in "mild_FRANKEN_harm_picks.csv", which just contains an integer in every row. Loop through mild_FRANKEN_compact_df, and for each row, look at the "event" column, which is a list of event strings. Use the integer in the corresponding row of mild_FRANKEN_harm_picks.csv to pick out one of the events from the "event" list. Then create a new dataframe called mild_FRANKEN_primary_harm_df, which has the same columns as mild_FRANKEN_compact_df, but the "event" column is now just the single event string that was picked out using the integer from mild_FRANKEN_harm_picks.csv.

harm_picks_df = pd.read_csv("mild_FRANKEN_harm_picks.csv")
mild_FRANKEN_primary_harm_df = mild_FRANKEN_compact_df.copy()
mild_FRANKEN_primary_harm_df["picked_event"] = None
for idx, row in mild_FRANKEN_primary_harm_df.iterrows():
    pick_idx = harm_picks_df.iloc[idx]["pick"]
    mild_FRANKEN_primary_harm_df.at[idx, "picked_event"] = row["events"][pick_idx]
    mild_FRANKEN_primary_harm_df.at[idx, "picked_event_idx"] = int(pick_idx)

# reorder the columns to put picked_event right after scenario_text for easier reference
mild_FRANKEN_primary_harm_df = mild_FRANKEN_primary_harm_df[["SID", "intensity", "causal_condition", "scenario_text", "events", "picked_event", "picked_event_idx", "option", "being", "C", "I", "K", "utility", "deontic", "avg_permissibility_rating", "avg_intention_rating"]]
print("Mild_FRANKEN_primary_harm_df:")
display(HTML(mild_FRANKEN_primary_harm_df[0:2].to_html()))
print(f"Total number of rows in mild_FRANKEN_primary_harm_df: {len(mild_FRANKEN_primary_harm_df)}")

# save this as mild_FRANKEN_primary_harm_df.csv for easier reference in the future
mild_FRANKEN_primary_harm_df.to_csv("mild_FRANKEN_primary_harm_df.csv", index=False)

Mild_FRANKEN_primary_harm_df:

Total number of rows in mild_FRANKEN_primary_harm_df: 80

### Expand the DF above if you want to see what primary harm I picked for each of the 80 scenarios!
### (Can drop some columns and re-print it for less visual crowding if you need!)

# Integrating Exp 1 human harm/good ratings

## Load in raw Exp 1 data

In [8]:
# load raw exp1 data into a df. Read the json file ../../human_data/franken/exp1_harm-vs-good-rating/exp1_unique_stimuli.json and display that dataframe:
exp1_raw_df = []
with open("../../human_data/franken/exp1_harm-vs-good-rating/exp1_unique_stimuli.json", 'r') as f:
    exp1_raw_df = json.load(f)
exp1_raw_df = pd.DataFrame(exp1_raw_df).drop(columns=['n_likert_ratings'])
display(HTML(exp1_raw_df[0:25].to_html()))

## Exp1 was done over both mild + intense, so we need a compact version of the combined Franken DF

In [9]:
# create a compact version of all_FRANKEN_df by collecting all the rows per scenario into a one row. You can find all the rows that belong to a scenario by finding all the rows that have the same SID and causal condition. The df will have all the rows that are in all_FRANKEN_df, but instead of 'event', we will have 'events' where values are a list of all the event strings. Then, values in the C, I, K columns will also be lists of the corresponding C, I, K values for each event, and the utility column will contain a list of dictionaries, one dict for each event. The intensity, causal_condition columns will just take the value from the first row of the scenario group since they are the same across all rows of the same scenario.
all_FRANKEN_compact_df = all_FRANKEN_df.groupby(["SID", "causal_condition", "option", "being", "intensity", "deontic"]).agg({
    "event": list,
    "C": list,
    "I": list,
    "K": list,
    "utility": list
}).reset_index()
# reorder the order of the columns to be SID, intensity, causal_condition, option, events, being, C, I, K, utility
all_FRANKEN_compact_df = all_FRANKEN_compact_df[["SID", "intensity", "causal_condition", "option", "event", "being", "C", "I", "K", "utility", "deontic"]]
# rename the "event" column to "events" since it now contains a list of events
all_FRANKEN_compact_df = all_FRANKEN_compact_df.rename(columns={"event": "events"})

# last thing -- bring in the original scenario text into the all_FRANKEN_compact_df for easier reference. We need to get them from the JSONs in ../../scenarios_inputs/franken/conditions_mild_harm_mild_good/ and ../../scenarios_inputs/franken/conditions_severe_harm_very_good/ where we have eight JSON files corresponding to the eight causal conditions (files have the same names as the causal conditions in the all_FRANKEN_compact_df).
scenario_texts = {}
for intensity in intensities:
    for causal_condition in causal_conditions:
        with open(f"../../scenarios_inputs/franken/conditions_{intensity}/{causal_condition}.json", 'r') as f:
            scenarios = json.load(f)
            for scenario in scenarios:
                scenario_texts[(intensity, scenario["id"], causal_condition)] = scenario["text"]
# now create a new column in all_FRANKEN_compact_df called "scenario_text" and fill it by matching the intensity, SID, and causal_condition with the keys in scenario_texts
# (note: the key must include intensity since mild and severe share the same causal_condition names -- otherwise the two would overwrite each other)
all_FRANKEN_compact_df["scenario_text"] = all_FRANKEN_compact_df.apply(lambda row: scenario_texts.get((row["intensity"], row["SID"], row["causal_condition"]), "N/A"), axis=1)
# reorder the columns to put scenario_text right after causal_condition for easier reference
all_FRANKEN_compact_df = all_FRANKEN_compact_df[["SID", "intensity", "causal_condition", "scenario_text", "option", "events", "being", "C", "I", "K", "utility", "deontic"]]
# group the rows by intensity, causal condition, and then SID:
all_FRANKEN_compact_df = all_FRANKEN_compact_df.groupby(["intensity", "causal_condition", "SID"]).first().reset_index()
print("All_FRANKEN_compact_df with scenario_text column added:")
display(HTML(all_FRANKEN_compact_df[0:2].to_html()))
print(f"Total number of rows in all_FRANKEN_compact_df: {len(all_FRANKEN_compact_df)}")

All_FRANKEN_compact_df with scenario_text column added:

Total number of rows in all_FRANKEN_compact_df: 160

## Match Franken compact DF with Exp 1 df by matching background sentence

`exp1_raw_df`'s `background` field (e.g. *"Maya has the opportunity to renovate a park in the city."*) is basically identical to the **second sentence** of our `scenario_text` (e.g. *"I have the opportunity to renovate a park in the city."*) in `all_FRANKEN_compact_df` -- we can match with this.

Caveat: exp1's stimuli were only ever written in the `_action_yes_stories` phrasing, so the `_prevention_no_stories` rows have no background sentence to match against and are expected to stay unmatched (NaN) -- that's fine.

In [10]:
import re
from difflib import SequenceMatcher

def second_sentence(text):
    """The 2nd sentence of scenario_text is always the 'I have the opportunity to ...' sentence."""
    sentences = re.split(r"(?<=[.!?])\s+", text)
    return sentences[1].strip() if len(sentences) > 1 else None

def drop_subject(sentence, n_words=2):
    """Drops the leading subject + verb ('Maya has' / 'I have') so the two phrasings compare directly."""
    return " ".join(sentence.split()[n_words:])

exp1_raw_df["stripped_background"] = exp1_raw_df["background"].apply(drop_subject)

strength_map = {"mild_harm_mild_good": "mild", "severe_harm_very_good": "severe"}

all_FRANKEN_exp1matched_df = all_FRANKEN_compact_df.copy()
all_FRANKEN_exp1matched_df["avg_harm_rating"] = np.nan
all_FRANKEN_exp1matched_df["avg_good_rating"] = np.nan

for idx, row in all_FRANKEN_exp1matched_df.iterrows():
    if "_action_yes_stories" not in row["causal_condition"]:
        continue  # exp1 stimuli were only phrased for the action_yes stories -- prevention_no rows stay NaN

    stripped_row_sentence = drop_subject(second_sentence(row["scenario_text"]))
    strength = strength_map[row["intensity"]]
    structure = "coc" if row["causal_condition"].startswith("coc") else "cc"
    candidates = exp1_raw_df[(exp1_raw_df["strength"] == strength) & (exp1_raw_df["structure"] == structure)]

    for rating_type, col in [("harm", "avg_harm_rating"), ("good", "avg_good_rating")]:
        subcandidates = candidates[candidates["type"] == rating_type]
        ratios = subcandidates["stripped_background"].apply(lambda bg: SequenceMatcher(None, stripped_row_sentence, bg).ratio())
        best_idx = ratios.idxmax()
        all_FRANKEN_exp1matched_df.at[idx, col] = exp1_raw_df.at[best_idx, "avg_likert_rating"]

print("all_FRANKEN_exp1matched_df (background-sentence matching):")
display(HTML(all_FRANKEN_exp1matched_df[all_FRANKEN_exp1matched_df["avg_harm_rating"].notna()][0:1].to_html()))
print(f"Total number of rows in all_FRANKEN_exp1matched_df: {len(all_FRANKEN_exp1matched_df)}")
print(f"Rows with both avg_harm_rating and avg_good_rating filled in: {all_FRANKEN_exp1matched_df[['avg_harm_rating', 'avg_good_rating']].notna().all(axis=1).sum()} / {len(all_FRANKEN_exp1matched_df)} -- the '_prevention_no_stories' rows are NaN because exp1 stimuli were only phrased for the action_yes stories.")

# save this as all_FRANKEN_exp1matched_df.csv for easier reference in the future
all_FRANKEN_exp1matched_df.to_csv("all_FRANKEN_exp1matched_df.csv", index=False)

all_FRANKEN_exp1matched_df (background-sentence matching):

Total number of rows in all_FRANKEN_exp1matched_df: 160
Rows with both avg_harm_rating and avg_good_rating filled in: 80 / 160 -- the '_prevention_no_stories' rows are NaN because exp1 stimuli were only phrased for the action_yes stories.

In [11]:
# match this with the human ratings from exp2. Create a new dataframe called all_FRANKEN_exp1exp2matched_df, which has the same columns as all_FRANKEN_exp1matched_df, but with two new columns: avg_permissibility_rating and avg_intention_rating whose values will come from mild_FRANKEN_compact_df. Fill these columns by matching the intensity, causal_condition, scenario_text, option, and events columns with the corresponding columns in mild_FRANKEN_compact_df.

# create a new dataframe to hold the merged data
all_FRANKEN_exp1exp2matched_df = all_FRANKEN_exp1matched_df.copy()
# create new columns for avg_permissibility_rating and avg_intention_rating in the merged_df and initialize them with NaN
all_FRANKEN_exp1exp2matched_df["avg_permissibility_rating"] = np.nan
all_FRANKEN_exp1exp2matched_df["avg_intention_rating"] = np.nan

# loop through each row in the merged_df and find the corresponding avg ratings from mild_FRANKEN_compact_df
for idx, row in all_FRANKEN_exp1exp2matched_df.iterrows():
    intensity = row["intensity"]
    causal_condition = row["causal_condition"]
    scenario_text = row["scenario_text"]
    option = row["option"]
    events = row["events"]

    # find the matching row in mild_FRANKEN_compact_df
    match = mild_FRANKEN_compact_df[
        (mild_FRANKEN_compact_df["intensity"] == intensity) &
        (mild_FRANKEN_compact_df["causal_condition"] == causal_condition) &
        (mild_FRANKEN_compact_df["scenario_text"] == scenario_text) &
        (mild_FRANKEN_compact_df["option"] == option) &
        (mild_FRANKEN_compact_df["events"].apply(lambda x: x == events))
    ]

    if not match.empty:
        all_FRANKEN_exp1exp2matched_df.at[idx, "avg_permissibility_rating"] = match.iloc[0]["avg_permissibility_rating"]
        all_FRANKEN_exp1exp2matched_df.at[idx, "avg_intention_rating"] = match.iloc[0]["avg_intention_rating"]

print("all_FRANKEN_exp1exp2matched_df (background-sentence matching + human ratings):")
display(HTML(all_FRANKEN_exp1exp2matched_df[0:1].to_html()))
print(f"Total number of rows in all_FRANKEN_exp1exp2matched_df: {len(all_FRANKEN_exp1exp2matched_df)}")
# drop all rows where avg_permissibility_rating or avg_intention_rating is NaN
all_FRANKEN_exp1exp2matched_df = all_FRANKEN_exp1exp2matched_df.dropna(subset=["avg_permissibility_rating", "avg_intention_rating", "avg_harm_rating", "avg_good_rating"])
print(f"Total number of rows in all_FRANKEN_exp1exp2matched_df after dropping rows with NaN in exp1 and exp2 ratings: {len(all_FRANKEN_exp1exp2matched_df)} \n-- none of the 'severe' intensity rows have exp2 ratings (halved), \n none of the 'prevention_no_stories' rows i.e. omission rows have exp1 ratings (halved again)")  
# save this as all_FRANKEN_exp1exp2matched_df.csv for easier reference in the future
all_FRANKEN_exp1exp2matched_df.to_csv("all_FRANKEN_exp1exp2matched_df.csv", index=False)

all_FRANKEN_exp1exp2matched_df (background-sentence matching + human ratings):

Total number of rows in all_FRANKEN_exp1exp2matched_df: 160
Total number of rows in all_FRANKEN_exp1exp2matched_df after dropping rows with NaN in exp1 and exp2 ratings: 40
-- none of the 'severe' intensity rows have exp2 ratings (halved),
 none of the 'prevention_no_stories' rows i.e. omission rows have exp1 ratings (halved again)